travis:
  secure:
    BINSTAR_TOKEN: oIpcl6H3m548OXQ3vua9nRru/471aP8dg2RT+2K5D8t3oCfl/d1G7/956Rpsphc+HTaOKpLWPfxDJuuFYIn7dq7GwHz5+U9O/etEHhA/VWnWCqS8JktTpoyQZCAFzI1EBTRJPmpszFTxCS5lRMVtnO3Q3Z1nm+tgHC5nHI/Y+7AVS1ZE2c+RkFhsGK6UwwLRk5jZeZHZSOJJPTQw9ezYRY2ZIUE3O5eeeSu8AcamcUgzgMJO+OnTNTw7p+6ZD1vABSqYOlOPq49a240hg3nC1aExLfWfVc+y9NqDrs1nr2R0S19gsaUkTgHkZdii15w7aGqPtCyhN1HKSkZF+9E5LVxeZHf4t8oPyohsluEiOJk3lSUlaCNeJebhhnf6A9PFJG3jDgW4Fxw7LlUHgmfaxefXOeJDUZEaYYqEjUch/VAwi4u2Vxhgm7n4SlP6EhIDjoFwBag6ddePGLbv1NZh4dV2gKtV9XMoHJFvcxUZulWwA+yGn2lXjJ2mM5iwf8aPhE0FopM4dBY0EXF+9gWVHIvd0fHEIwjNqrjohx+GitUlVmz1MhmOzHeD6vwa+o/A4isnKgEoDwp09t9bR5PhSIBYBnwPeArlOvPyM8vxnQwy7z5WkV5X04WW7yeFh9F/HTpuJA3BsVtBTKVawb3NJSTovIECWPriokFt1OordIY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
