travis:
  secure:
    BINSTAR_TOKEN: PODUADPVUe2Wpp2sjilLUD2ZAO4NCch7oGBdpvlMIEZMNBugQXKasdKUf5226Tvu1cq1Ok6pmhf7YhjRdEcWu12aJw/GX6Cix1oG1SaI9u7yVkMXEkArgIgGAVUXJmiQX4JlMIwF1fysMVf8JBd2/D/3ewvNWN0y7MpNczcz2SvnzK2Ukf4tbyuqmBv3Xctc3918O9tS6ajpIXD0YQi8xlIQGTPVgQC5QpS3A0ryngqjQ1DL+m+fm2G8IzNgg3iieEfJsy8FvBNypF8KUtg7CJXjdbBeCcFrrdB9EmF8zO0u9teirfZcPNIPkLGRaFTJt/MPCKRvyEVEqs6QKbMDGD5aRS6/2ScUKFMgHPW3Dr8V8ILN3wDnMxogpPt6S0Wy83mcI5zn/wcU0Fah9PAO/KpYARIjhj9m/6+bX+efzGjqiyU3CMPzQy3SfHvb+x+P2cllngzkXfDcZ8Q4c/PcEXmHYQqik+VjDqj2+zUnl3pIYAqAZZMf//cMFOOI0D5yRIyCdjN2DjWHJQ/XLZW+gl1zInWDoNy5qEbokK28NGHhukJXuEQ52NEZizuqkw/yng/fxonKu9Zq4Pks3h4dORQ2lMQVpgSSmonbPgeukwTHhu38yJKuyh3pp+J4KF9s5pthRKrUCDkAjjUGDhFbrMB4Wsm//BgnuNtCSxhe6DA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
